### ISSUE TITLE
There is not hippiehug >= 0.1.1 in pypi, required in setup.py

### ISSUE THREAD

**Issue by juga0** [claimchain/claimchain-core#2]

**Comment by bogdan-kulynych** [comment]
It indeed is not pypi, it has to be installed manually from Github. Have you tried the instructions from README, or they did not work.

Right now I am working on fixing this by moving to a [reimplementation of hippehug](https://github.com/bogdan-kulynych/hippiepug).

**Comment by juga0** [comment]
Ah, right, with the version in the ``requirements/base.txt`` (https://github.com/gdanezis/rousseau-chain@dc3cf26bc0281e9b01352316da2e655b0ed84f45&subdirectory=hippiehug-package), it can be installed, though not with the version in ``setup.py`` (hippiehug >= 0.1.1)

**Comment by hpk42** [comment]
azul and me just released hippiehug-0.1.3 and also there is now a claimchain-0.3.1 which requires it.
