### ISSUE TITLE
petlib requirement can not be installed, fails to compile

### ISSUE THREAD

**Issue by juga0** [claimchain/claimchain-core#3]
build/temp.linux-x86_64-2.7/petlib._petlib.c:521:19: error: invalid application of ‘sizeof’ to incomplete type ‘HMAC_CTX {aka struct hmac_ctx_st}’
         return sizeof(HMAC_CTX);
                       ^~~~~~~~

**Comment by bogdan-kulynych** [comment]
Please check the [petlib installation instructions](https://github.com/gdanezis/petlib). E.g., on Ubuntu make sure you have installed python-dev, libssl-dev, libffi-dev.

**Comment by juga0** [comment]
Thanks for the suggestions. I already had those libraries installed.
